namespace GenshinPatcher.Tools.Shortcut.Win32.Structure;

public enum ValueTypes
{
    Empty,
    Null,
    Short,
    Integer,
    Float,
    Double,
    Currency,
    Date,
    BStr,
    HResult,
    Bool,
    Byte,
    UnsignedByte,
    UnsignedShort,
    UnsignedInteger,
    Long,
    UnsignedLong,
    Int,
    Uint,
    AnsiString,
    UnicodeString,
    FileTime,
    Blob,
    Stream,
    Storage,
    StreamedObject,
    StoredObject,
    BlobObject,
    PropertyValue,
    ClassId,
    VersionedStream,
}